import type { Answers } from "@/types";

/**
 * Synthesizes the 10 raw interview answers into a permanent, AI-facing
 * Markdown profile. This performs light NLP-style normalization —
 * trimming filler, merging repeated ideas, and rewriting first-person
 * answers into declarative instructions an assistant can follow —
 * rather than echoing the user's raw text back verbatim.
 */

const FILLER_PATTERNS = [
  /^\s*(um,?|uh,?|well,?|so,?|like,?)\s+/i,
  /\s+(i guess|i think|kind of|sort of|you know)\b/gi,
];

function clean(text: string): string {
  let result = text.trim();
  for (const pattern of FILLER_PATTERNS) {
    result = result.replace(pattern, "");
  }
  return result.replace(/\s+/g, " ").trim();
}

function splitIdeas(text: string): string[] {
  return clean(text)
    .split(/[,.;]\s*|\band\b/i)
    .map((s) => s.trim())
    .filter((s) => s.length > 2);
}

function dedupe(items: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    const key = item.toLowerCase().replace(/[^a-z0-9]/g, "");
    if (key.length < 3 || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

function bulletList(items: string[]): string {
  const deduped = dedupe(items);
  if (deduped.length === 0) return "- Not specified.";
  return deduped.map((i) => `- ${i.charAt(0).toUpperCase() + i.slice(1)}`).join("\n");
}

function fallback(value: string | undefined, defaultText: string): string {
  const v = value ? clean(value) : "";
  return v.length > 0 ? v : defaultText;
}

export function generateProfile(answers: Answers): string {
  const a = (id: number) => answers[id] ?? "";

  const purpose = bulletList(splitIdeas(a(1)));
  const interests = bulletList(splitIdeas(a(2)));
  const knowledge = fallback(
    a(3),
    "Mixed familiarity across topics; calibrate explanations per subject rather than assuming a fixed level."
  );
  const communication = fallback(
    a(4),
    "No strong preference stated; default to clear, respectful, moderately concise language."
  );
  const learning = fallback(
    a(5),
    "No strong preference stated; default to a mix of explanation and concrete examples."
  );
  const preferredResponses = bulletList(splitIdeas(a(6)));
  const avoid = bulletList(splitIdeas(a(7)));
  const decisionStyle = fallback(
    a(8),
    "When giving advice, state a clear recommendation and briefly note the key tradeoffs."
  );
  const constraints = bulletList(splitIdeas(a(9)));
  const permanentNotes = fallback(
    a(10),
    "No additional permanent notes provided."
  );

  const generatedOn = new Date().toISOString().split("T")[0];

  return `# AI Personalization Profile

> Generated by Noetis on ${generatedOn}. This file describes how an AI assistant should communicate with this person. Treat every section below as a standing instruction, not a transcript of a conversation.

## Purpose

Primary reasons this person uses AI assistants:

${purpose}

## Current Interests

Topics currently most relevant to this person — prioritize these when giving examples or suggestions:

${interests}

## Knowledge Level

${knowledge}

## Communication Style

${communication}

## Learning Style

${learning}

## Preferred Responses

What makes a response genuinely useful to this person:

${preferredResponses}

## Things to Avoid

Patterns that have frustrated this person in past AI interactions — do not repeat them:

${avoid}

## Decision-Making Style

${decisionStyle}

## Preferences & Constraints

${constraints}

## Permanent Notes

${permanentNotes}

---

*This profile is portable and can be pasted into the custom instructions or system prompt of ChatGPT, Claude, Gemini, Grok, DeepSeek, Llama, Mistral, or any other AI assistant.*
`;
}
