import type { DocumentGenerationResult } from "@/types";

const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const MODEL = "meta-llama/llama-3.3-70b-instruct:free";

/**
 * Deterministic fallback in case the OpenRouter call fails or API key is missing.
 */
function buildFallbackMarkdown(projectName: string, projectMarkdown: string, personaMarkdown: string): string {
  const cleanPersona = personaMarkdown
    .split("\n")
    .filter((line) => !line.startsWith("# ") && !line.startsWith("*This profile"))
    .join("\n")
    .trim();

  return `# Skill: ${projectName}

> Generated by Noetis (AI fallback). This file describes permanent, project-level knowledge for ${projectName}. Treat every section below as a standing instruction for any AI assistant working on this project.

${projectMarkdown.trim()}

## Communication Preferences

${cleanPersona}

---

*This Skill is portable and can be pasted into the custom instructions, system prompt, or project knowledge of ChatGPT, Claude, Gemini, Grok, DeepSeek, Llama, Mistral, or any other AI assistant.*
`;
}

/**
 * Intelligently combines a Project Profile (Project.md) and a Persona Profile (Personal.md)
 * into a single unified Skill.md instructions document using OpenRouter.
 */
export async function generateCombinedSkill(
  projectName: string,
  projectMarkdown: string,
  personaMarkdown: string
): Promise<DocumentGenerationResult> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return {
      markdown: buildFallbackMarkdown(projectName, projectMarkdown, personaMarkdown),
      usedAI: false,
    };
  }

  const prompt = `You are an expert software architect and technical writer. 
Your job is to synthesize two documents:
1. A Project Profile (Project.md) containing the project's tech stack, architecture, conventions, constraints, and features.
2. An AI Communication Profile (Personal.md) describing how the user personally prefers AI assistants to communicate with them (rules, style, response length, detail).

You need to merge these into a single, cohesive, optimized instructions document called "Skill.md" for the project "${projectName}".
This document must act as a set of standing instructions for any AI assistant working on this project.

Rules:
- Do NOT include any intro or outro prose. Output ONLY the clean Markdown document starting directly with the title.
- Integrate the technical stack, codebase structure, features, coding standards, security constraints, and deployment details into a clear, structured set of developer rules.
- Adapt the user's communication preferences from the Personal.md file so they directly align with and reference the development workflow of this project (e.g., "When explaining the Next.js architecture, keep explanations concise and focus on code snippets as preferred by the user").
- Produce a single, unified Markdown file. Do not wrap the output in markdown code fences.

Project Profile (Project.md):
${projectMarkdown}

AI Communication Profile (Personal.md):
${personaMarkdown}
`;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15000);

  try {
    const res = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        messages: [{ role: "user", content: prompt }],
        temperature: 0.3,
      }),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);

    if (!res.ok) {
      console.error("OpenRouter combine skill failed:", res.status, await res.text());
      return {
        markdown: buildFallbackMarkdown(projectName, projectMarkdown, personaMarkdown),
        usedAI: false,
      };
    }

    const data = await res.json();
    const content = data?.choices?.[0]?.message?.content;
    if (!content || typeof content !== "string") {
      return {
        markdown: buildFallbackMarkdown(projectName, projectMarkdown, personaMarkdown),
        usedAI: false,
      };
    }

    return { markdown: content.trim(), usedAI: true };
  } catch (err) {
    clearTimeout(timeoutId);
    console.error("OpenRouter combine skill error:", err);
    return {
      markdown: buildFallbackMarkdown(projectName, projectMarkdown, personaMarkdown),
      usedAI: false,
    };
  }
}
