import type { ProjectInterviewAnswers } from "@/types/skill";

/**
 * Synthesizes the 6 Adaptive Project Interview answers — plus an optional
 * Persona's communication profile — into a permanent, provider-independent
 * Skill.md.
 */

const FILLER_PATTERNS = [
  /^\s*(um,?|uh,?|well,?|so,?|like,?)\s+/i,
  /\s+(i guess|i think|kind of|sort of|you know)\b/gi,
];

function clean(text: string): string {
  let result = text.trim();
  for (const pattern of FILLER_PATTERNS) {
    result = result.replace(pattern, "");
  }
  return result.replace(/\s+/g, " ").trim();
}

function splitIdeas(text: string): string[] {
  return clean(text)
    .split(/[,.;]\s*|\band\b/i)
    .map((s) => s.trim())
    .filter((s) => s.length > 2);
}

function dedupe(items: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    const key = item.toLowerCase().replace(/[^a-z0-9]/g, "");
    if (key.length < 3 || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

function bulletList(items: string[]): string {
  const deduped = dedupe(items);
  if (deduped.length === 0) return "- Not specified.";
  return deduped.map((i) => `- ${i.charAt(0).toUpperCase() + i.slice(1)}`).join("\n");
}

function fallback(value: string | undefined, defaultText: string): string {
  const v = value ? clean(value) : "";
  return v.length > 0 ? v : defaultText;
}

interface GenerateSkillOptions {
  projectName: string;
  answers: ProjectInterviewAnswers;
  /** The user's Persona markdown (AI_PROFILE.md), if one was selected — folded
   * in as a "Communication Preferences" section so the Skill carries both
   * project knowledge and how this person likes to be talked to. */
  personaMarkdown?: string | null;
}

function extractPersonaBody(personaMarkdown: string): string {
  return personaMarkdown
    .split("\n")
    .filter((line) => !line.startsWith("# ") && !line.startsWith("*This profile"))
    .join("\n")
    .trim();
}

export function generateSkill({ projectName, answers, personaMarkdown }: GenerateSkillOptions): string {
  const a = (id: number) => answers[id] ?? "";

  const overview = fallback(a(1), "No project overview provided yet.");
  const stack = bulletList(splitIdeas(a(2)));
  const features = bulletList(splitIdeas(a(3)));
  const standards = fallback(a(4), "No coding standards or testing strategy documented yet.");
  const constraints = fallback(a(5), "No security, constraints, or business rules documented yet.");
  const operations = fallback(a(6), "No operations, deployment, or performance considerations documented yet.");

  const generatedOn = new Date().toISOString().split("T")[0];
  const name = projectName.trim() || "Untitled project";

  const communicationSection = personaMarkdown
    ? `## Communication Preferences

${extractPersonaBody(personaMarkdown)}

`
    : "";

  return `# Skill: ${name}

> Generated by Noetis on ${generatedOn}. This file describes permanent, project-level knowledge for ${name}. Treat every section below as a standing instruction for any AI assistant working on this project — not a transcript of a conversation.

## Project Overview & Users

${overview}

## Tech Stack & Architecture

${stack}

## Core Features & AI Integration

${features}

## Coding Standards & Testing

${standards}

## Security, Constraints & Business Rules

${constraints}

## Operations, Deployment & Performance

${operations}

${communicationSection}---

*This Skill is portable and can be pasted into the custom instructions, system prompt, or project knowledge of ChatGPT, Claude, Gemini, Grok, DeepSeek, Llama, Mistral, or any other AI assistant.*
`;
}
