"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { Archive, Home, Layers, Plus, Search, Sparkles, Star, X } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";
import { Button } from "@/components/ui/button";
import { SkillCard } from "@/components/skill/skill-card";
import { SkillViewDialog } from "@/components/skill/skill-view-dialog";
import { useSkills } from "@/lib/skills/use-skills";
import type { Skill } from "@/types/skill";

export default function SkillsPage() {
  const {
    hydrated,
    skills,
    renameSkill,
    setSkillTags,
    toggleFavorite,
    togglePinned,
    toggleArchived,
    duplicateSkill,
    deleteSkill,
    restoreSkillVersion,
  } = useSkills();
  const [viewing, setViewing] = useState<Skill | null>(null);
  const [query, setQuery] = useState("");
  const [activeTag, setActiveTag] = useState<string | null>(null);
  const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);
  const [showArchived, setShowArchived] = useState(false);

  const allTags = useMemo(() => {
    const seen = new Set<string>();
    for (const s of skills) for (const t of s.tags) seen.add(t);
    return Array.from(seen).sort((a, b) => a.localeCompare(b));
  }, [skills]);

  const filteredSkills = useMemo(() => {
    const q = query.trim().toLowerCase();
    return skills
      .filter((s) => (showArchived ? s.archived : !s.archived))
      .filter((s) => {
        const matchesTag = !activeTag || s.tags.includes(activeTag);
        const matchesFavorite = !showFavoritesOnly || s.favorite;
        const matchesQuery =
          q.length === 0 ||
          s.name.toLowerCase().includes(q) ||
          s.projectName.toLowerCase().includes(q) ||
          s.markdown.toLowerCase().includes(q) ||
          s.tags.some((t) => t.toLowerCase().includes(q));
        return matchesTag && matchesFavorite && matchesQuery;
      })
      .sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
        return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
      });
  }, [skills, query, activeTag, showFavoritesOnly, showArchived]);

  if (!hydrated) return null;

  const handleEditTags = (skill: Skill) => {
    const raw = window.prompt("Edit tags (comma-separated)", skill.tags.join(", "));
    if (raw === null) return;
    const tags = Array.from(
      new Set(
        raw
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean)
      )
    );
    setSkillTags(skill.id, tags);
  };

  const activeCount = skills.filter((s) => !s.archived).length;

  return (
    <div className="relative z-10 min-h-screen">
      <header className="flex items-center justify-between border-b border-[var(--border)] px-6 py-4 sm:px-10">
        <div className="flex items-center gap-4">
          <Link
            href="/"
            className="flex items-center gap-1.5 rounded-full border border-[var(--border)] bg-white/30 px-3 py-1.5 text-small font-medium text-[var(--text-secondary)] hover:text-[var(--text-primary)] dark:bg-white/5"
          >
            <Home className="h-3.5 w-3.5" />
            Home
          </Link>
          <span className="text-[var(--border)]">/</span>
          <span className="text-small font-semibold text-[var(--text-primary)]">Knowledge / Skills</span>
        </div>
        <ThemeToggle />
      </header>

      <div className="mx-auto max-w-[1100px] px-6 py-14 sm:px-10">
        <div className="mb-10 flex flex-col items-center text-center">
          <div className="mb-5 flex h-14 w-14 items-center justify-center rounded-full bg-[var(--accent)]/15">
            <Layers className="h-6 w-6 text-[var(--accent)]" strokeWidth={1.75} />
          </div>
          <h1 className="text-section text-[var(--text-primary)]">Your Skills Library</h1>
          <p className="mt-3 max-w-[520px] text-body text-[var(--text-secondary)]">
            Permanent, project-level knowledge — stack, architecture, conventions, rules — generated by
            the Adaptive Project Interview into a Skill.md any AI assistant can read.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <Link href="/">
              <Button variant="glass">
                <Plus className="h-4 w-4" />
                New Personal Profile
              </Button>
            </Link>
            <Link href="/skills/new?mode=project">
              <Button variant="glass">
                <Plus className="h-4 w-4" />
                New Project Profile
              </Button>
            </Link>
            <Link href="/skills/combine">
              <Button>
                <Sparkles className="h-4 w-4 text-[var(--accent)]" />
                New Combined Skill
              </Button>
            </Link>
          </div>
        </div>

        {activeCount === 0 && !showArchived ? (
          <div className="flex flex-col items-center gap-4 rounded-xl3 border border-dashed border-[var(--border)] py-20 text-center">
            <Sparkles className="h-6 w-6 text-[var(--text-secondary)]" />
            <p className="text-body text-[var(--text-secondary)]">
              No Skills yet. Create a personal profile, a project profile, or combine them to get started.
            </p>
            <div className="flex flex-wrap justify-center gap-3">
              <Link href="/">
                <Button variant="glass">New Personal Profile</Button>
              </Link>
              <Link href="/skills/new?mode=project">
                <Button variant="glass">New Project Profile</Button>
              </Link>
              <Link href="/skills/combine">
                <Button>New Combined Skill</Button>
              </Link>
            </div>
          </div>
        ) : (
          <>
            <div className="mb-6 flex flex-col gap-4">
              <div className="relative mx-auto w-full max-w-[440px]">
                <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-secondary)]" />
                <input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Search skills…"
                  className="w-full rounded-full border border-[var(--border)] bg-white/40 py-2.5 pl-11 pr-10 text-small text-[var(--text-primary)] outline-none focus:border-[var(--accent)] dark:bg-white/5"
                />
                {query.length > 0 && (
                  <button
                    type="button"
                    aria-label="Clear search"
                    onClick={() => setQuery("")}
                    className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full p-1 text-[var(--text-secondary)] hover:bg-black/5 dark:hover:bg-white/5"
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                )}
              </div>

              <div className="flex flex-wrap items-center justify-center gap-2">
                <button
                  type="button"
                  onClick={() => setShowFavoritesOnly((v) => !v)}
                  className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[12px] font-medium transition-colors ${
                    showFavoritesOnly
                      ? "bg-[var(--accent)] text-white"
                      : "bg-black/5 text-[var(--text-secondary)] hover:bg-black/10 dark:bg-white/5 dark:hover:bg-white/10"
                  }`}
                >
                  <Star className="h-3 w-3" />
                  Favorites
                </button>
                <button
                  type="button"
                  onClick={() => setShowArchived((v) => !v)}
                  className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[12px] font-medium transition-colors ${
                    showArchived
                      ? "bg-[var(--accent)] text-white"
                      : "bg-black/5 text-[var(--text-secondary)] hover:bg-black/10 dark:bg-white/5 dark:hover:bg-white/10"
                  }`}
                >
                  <Archive className="h-3 w-3" />
                  {showArchived ? "Viewing archived" : "Show archived"}
                </button>
                {allTags.map((tag) => (
                  <button
                    key={tag}
                    type="button"
                    onClick={() => setActiveTag(activeTag === tag ? null : tag)}
                    className={`rounded-full px-3 py-1.5 text-[12px] font-medium transition-colors ${
                      activeTag === tag
                        ? "bg-[var(--accent)] text-white"
                        : "bg-black/5 text-[var(--text-secondary)] hover:bg-black/10 dark:bg-white/5 dark:hover:bg-white/10"
                    }`}
                  >
                    {tag}
                  </button>
                ))}
              </div>
            </div>

            {filteredSkills.length === 0 ? (
              <div className="flex flex-col items-center gap-3 rounded-xl3 border border-dashed border-[var(--border)] py-16 text-center">
                <p className="text-body text-[var(--text-secondary)]">
                  No Skills match your search or filter.
                </p>
              </div>
            ) : (
              <motion.div layout className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
                <AnimatePresence>
                  {filteredSkills.map((skill) => (
                    <SkillCard
                      key={skill.id}
                      skill={skill}
                      onView={() => setViewing(skill)}
                      onRename={() => {
                        const name = window.prompt("Rename skill", skill.name);
                        if (name) renameSkill(skill.id, name);
                      }}
                      onEditTags={() => handleEditTags(skill)}
                      onToggleFavorite={() => toggleFavorite(skill.id)}
                      onTogglePinned={() => togglePinned(skill.id)}
                      onToggleArchived={() => toggleArchived(skill.id)}
                      onDuplicate={() => duplicateSkill(skill.id)}
                      onDelete={() => {
                        if (window.confirm(`Delete "${skill.name}"? This can't be undone.`)) {
                          deleteSkill(skill.id);
                        }
                      }}
                    />
                  ))}
                </AnimatePresence>
              </motion.div>
            )}
          </>
        )}
      </div>

      <AnimatePresence>
        {viewing && (
          <SkillViewDialog
            skill={viewing}
            onClose={() => setViewing(null)}
            onRestoreVersion={(versionIndex) => {
              restoreSkillVersion(viewing.id, versionIndex);
              setViewing(null);
            }}
          />
        )}
      </AnimatePresence>
    </div>
  );
}
