import type { Capsule } from "@/types/atlas";

/** Renders a Capsule as portable Markdown, ready to paste into any LLM's chat or system prompt. */
export function capsuleToMarkdown(capsule: Capsule): string {
  const lines: string[] = [];
  lines.push(`# Context Capsule: ${capsule.name}`);
  lines.push("");
  lines.push(`> Generated by Atlas on ${capsule.createdAt.split("T")[0]}. Paste this into a new conversation to bring the assistant up to speed.`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(capsule.summary);
  lines.push("");

  if (capsule.decisions.length > 0) {
    lines.push("## Key Decisions");
    lines.push("");
    for (const d of capsule.decisions) lines.push(`- ${d}`);
    lines.push("");
  }

  if (capsule.architectureNotes.length > 0) {
    lines.push("## Architecture");
    lines.push("");
    for (const a of capsule.architectureNotes) lines.push(`- ${a}`);
    lines.push("");
  }

  if (capsule.keyCode.length > 0) {
    lines.push("## Key Code");
    lines.push("");
    for (const snippet of capsule.keyCode) {
      lines.push(`_From: ${snippet.fromConversationTitle}_`);
      lines.push("");
      lines.push(`\`\`\`${snippet.language}`);
      lines.push(snippet.code);
      lines.push("```");
      lines.push("");
    }
  }

  if (capsule.keyMessages.length > 0) {
    lines.push("## Key Messages");
    lines.push("");
    for (const m of capsule.keyMessages) lines.push(`- ${m}`);
    lines.push("");
  }

  if (capsule.references.length > 0) {
    lines.push("## References");
    lines.push("");
    for (const r of capsule.references) lines.push(`- ${r}`);
    lines.push("");
  }

  return lines.join("\n");
}

export function capsuleFilename(name: string): string {
  const safe = name.trim().replace(/[^a-z0-9\-_ ]/gi, "").replace(/\s+/g, "_");
  return `${safe || "capsule"}_capsule.md`;
}
